# Generated by Django 3.2.10 on 2021-12-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_alter_language_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='nameInNativeScript',
            field=models.CharField(default='தமிழ்', max_length=20),
            preserve_default=False,
        ),
    ]
